### ISSUE TITLE
osx error: MSG_NOSIGNAL

### ISSUE THREAD

**Issue by reqshark** [sustrik/dillsocks#2]
```c
1:40 $ make
  CC       libdillsocks_la-cons.lo
  CC       libdillsocks_la-inproc.lo
  CC       libdillsocks_la-ip.lo
  CC       libdillsocks_la-ipc.lo
ipc.c:116:51: error: use of undeclared identifier 'MSG_NOSIGNAL'
            ssize_t sz = send(conn->fd, pos, len, MSG_NOSIGNAL);
```

`SO_NOSIGPIPE` is already set, so a local definition of this flag should accomodate osx

**Comment by sustrik** [comment]
I've replaced the old implementation with a new one (an experimental project, sorry!) but I've took care to address the MSG_NOSIGNAL problem in the new code. Thanks for reporting that!

**Comment by reqshark** [comment]
problem fixed thanks!
